export declare const TIP_CLASS_MAP: {
  store: string;
  img: string;
  detail: string;
  name: string;
  'icon--primary': string;
  distance: string;
  'distance--primary': string;
  addr: string;
  'icon--addr': string;
  'distance--secondary': string;
  address: string;
  'icon--secondary': string;
  'icon--instore': string;
  'icon--eventbeen': string;
  'icon--lately': string;
  'icon-state': string;
  'icon--jp': string;
  'icon--yp': string;
};
export declare function getActClass(useTipClass: boolean, args: any): any;
