/* Automatically generated by './script/component-config/generate-entry.js' */
import Button from './packages/press-button/press-button.vue';
import Cell from './packages/press-cell/press-cell.vue';
import Col from './packages/press-col/press-col.vue';
import IconPlus from './packages/press-icon-plus/press-icon-plus.vue';
import Image from './packages/press-image/press-image.vue';
import PopupPlus from './packages/press-popup-plus/press-popup-plus.vue';
import Toast from './packages/press-toast/press-toast.vue';
import Transition from './packages/press-transition/press-transition.vue';
import Calendar from './packages/press-calendar/press-calendar.vue';
import Checkbox from './packages/press-checkbox/press-checkbox.vue';
import CodeInput from './packages/press-code-input/press-code-input.vue';
import DatetimePicker from './packages/press-datetime-picker/press-datetime-picker.vue';
import Field from './packages/press-field/press-field.vue';
import PickerPlus from './packages/press-picker-plus/press-picker-plus.vue';
import Radio from './packages/press-radio/press-radio.vue';
import Rate from './packages/press-rate/press-rate.vue';
import Search from './packages/press-search/press-search.vue';
import Slider from './packages/press-slider/press-slider.vue';
import Stepper from './packages/press-stepper/press-stepper.vue';
import Switch from './packages/press-switch/press-switch.vue';
import Uploader from './packages/press-uploader/press-uploader.vue';
import ActionSheet from './packages/press-action-sheet/press-action-sheet.vue';
import DialogPlus from './packages/press-dialog-plus/press-dialog-plus.vue';
import DropdownMenu from './packages/press-dropdown-menu/press-dropdown-menu.vue';
import LoadingPlus from './packages/press-loading-plus/press-loading-plus.vue';
import Notify from './packages/press-notify/press-notify.vue';
import Overlay from './packages/press-overlay/press-overlay.vue';
import PopoverPlus from './packages/press-popover-plus/press-popover-plus.vue';
import ShareSheet from './packages/press-share-sheet/press-share-sheet.vue';
import SwipeCell from './packages/press-swipe-cell/press-swipe-cell.vue';
import Avatar from './packages/press-avatar/press-avatar.vue';
import Badge from './packages/press-badge/press-badge.vue';
import Barcode from './packages/press-barcode/press-barcode.vue';
import Card from './packages/press-card/press-card.vue';
import Circle from './packages/press-circle/press-circle.vue';
import Collapse from './packages/press-collapse/press-collapse.vue';
import CountDown from './packages/press-count-down/press-count-down.vue';
import CountTo from './packages/press-count-to/press-count-to.vue';
import Divider from './packages/press-divider/press-divider.vue';
import Empty from './packages/press-empty/press-empty.vue';
import Fab from './packages/press-fab/press-fab.vue';
import ImagePreview from './packages/press-image-preview/press-image-preview.vue';
import List from './packages/press-list/press-list.vue';
import NoticeBar from './packages/press-notice-bar/press-notice-bar.vue';
import Progress from './packages/press-progress/press-progress.vue';
import QRCode from './packages/press-q-r-code/press-q-r-code.vue';
import Skeleton from './packages/press-skeleton/press-skeleton.vue';
import Steps from './packages/press-steps/press-steps.vue';
import Sticky from './packages/press-sticky/press-sticky.vue';
import Swiper from './packages/press-swiper/press-swiper.vue';
import Tag from './packages/press-tag/press-tag.vue';
import Grid from './packages/press-grid/press-grid.vue';
import IndexBar from './packages/press-index-bar/press-index-bar.vue';
import NavBar from './packages/press-nav-bar/press-nav-bar.vue';
import Sidebar from './packages/press-sidebar/press-sidebar.vue';
import Tab from './packages/press-tab/press-tab.vue';
import Tabbar from './packages/press-tabbar/press-tabbar.vue';
import TreeSelect from './packages/press-tree-select/press-tree-select.vue';
import Dialog from './packages/press-dialog/press-dialog.vue';
import Icon from './packages/press-icon/press-icon.vue';
import Loading from './packages/press-loading/press-loading.vue';
import Pagination from './packages/press-pagination/press-pagination.vue';
import Picker from './packages/press-picker/press-picker.vue';
import Popover from './packages/press-popover/press-popover.vue';
import Popup from './packages/press-popup/press-popup.vue';

const components = [
  Button,
  Cell,
  Col,
  IconPlus,
  Image,
  PopupPlus,
  Toast,
  Transition,
  Calendar,
  Checkbox,
  CodeInput,
  DatetimePicker,
  Field,
  PickerPlus,
  Radio,
  Rate,
  Search,
  Slider,
  Stepper,
  Switch,
  Uploader,
  ActionSheet,
  DialogPlus,
  DropdownMenu,
  LoadingPlus,
  Notify,
  Overlay,
  PopoverPlus,
  ShareSheet,
  SwipeCell,
  Avatar,
  Badge,
  Barcode,
  Card,
  Circle,
  Collapse,
  CountDown,
  CountTo,
  Divider,
  Empty,
  Fab,
  ImagePreview,
  List,
  NoticeBar,
  Progress,
  QRCode,
  Skeleton,
  Steps,
  Sticky,
  Swiper,
  Tag,
  Grid,
  IndexBar,
  NavBar,
  Sidebar,
  Tab,
  Tabbar,
  TreeSelect,
  Dialog,
  Icon,
  Loading,
  Pagination,
  Picker,
  Popover,
  Popup,
];

const install = function (Vue, opts = {}) {
  components.forEach((component) => {
    Vue.component(component.name, component);
  });

  Vue.prototype.$PRESS = {
    size: opts.size || '',
    zIndex: opts.zIndex || 2000,
  };
};

if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  install,
  ...components,
};
