export declare const TIP_CLASS_MAP: {
  task: string;
  'header-right': string;
  'header-btn': string;
  'header-rule': string;
  content: string;
  'award-title': string;
  'award-list': string;
  'task-list': string;
  'match-title': string;
  'match-list': string;
  'match-item': string;
  'match-label': string;
  'match-meta': string;
  'match-image': string;
  'match-name': string;
  'match-awards': string;
  'task-item': string;
  'task-name': string;
  'task-box': string;
  'task-award-img': string;
  'btn--primary': string;
  'btn--secondary': string;
  'btn--text': string;
};
export declare function getActClass(useTipClass: boolean, args: any): any;
