export declare const TIP_CLASS_MAP: {
  cover: string;
  dialog: string;
  'dialog-phone': string;
  close: string;
  title: string;
  'title--phone': string;
  content: string;
  box: string;
  'phone-number': string;
  'code-wrap': string;
  'code-number': string;
  'code-btn': string;
  'code-btn--disabled': string;
  message: string;
  'treaty-wrap': string;
  'treaty-check': string;
  'treaty-terms': string;
  'treaty-desc': string;
  'button-wrap': string;
  'btn--cancel': string;
  'btn--medium-secondary': string;
  'btn--disabled': string;
  'btn--sure': string;
  'btn--medium-primary': string;
  'act-checkbox': string;
  'act-checkbox--checked': string;
};
export declare function getActClass(useTipClass: boolean, args: any): any;
