export declare const TIP_CLASS_MAP: {
  cover: string;
  dialog: string;
  'dialog--select': string;
  close: string;
  title: string;
  'title--select': string;
  content: string;
  'award-list': string;
  'award-item': string;
  'award-item--active': string;
  left: string;
  box: string;
  image: string;
  'info-wrap': string;
  name: string;
  tip: string;
  right: string;
  'select-button': string;
  bottom: string;
  buttons: string;
  btn: string;
  'btn--close': string;
  'btn--maxlarge-primary': string;
  'btn--disabled': string;
};
export declare function getActClass(useTipClass: boolean, args: any): any;
