// Auto Generated By Script. Do not Change it.
export const STYLE_LIST = [
  'cfm-vertical',
  'game-life',
  'gp-vertical',
  'gp',
  'hlddz-vertical',
  'hlddz',
  'lolm-lunar',
  'lolm-vertical',
  'lolm',
  'majiang-vertical',
  'majiang',
  'pvp-vertical',
  'pvp',
  'tlbb',
  'x5m-vertical',
  'zqnba',
];
