/* Automatically generated by './script/component-config/generate-entry.js' */
import Area from './packages/press-area/press-area.vue';
import AvatarGroup from './packages/press-avatar-group/press-avatar-group.vue';
import Avatar from './packages/press-avatar/press-avatar.vue';
import BackTop from './packages/press-back-top/press-back-top.vue';
import Badge from './packages/press-badge/press-badge.vue';
import Barcode from './packages/press-barcode/press-barcode.vue';
import Button from './packages/press-button/press-button.vue';
import Calendar from './packages/press-calendar/press-calendar.vue';
import Card from './packages/press-card/press-card.vue';
import CellGroup from './packages/press-cell-group/press-cell-group.vue';
import Cell from './packages/press-cell/press-cell.vue';
import CheckboxGroup from './packages/press-checkbox-group/press-checkbox-group.vue';
import Checkbox from './packages/press-checkbox/press-checkbox.vue';
import Circle from './packages/press-circle/press-circle.vue';
import CodeInput from './packages/press-code-input/press-code-input.vue';
import Col from './packages/press-col/press-col.vue';
import CollapseItem from './packages/press-collapse-item/press-collapse-item.vue';
import Collapse from './packages/press-collapse/press-collapse.vue';
import CountDown from './packages/press-count-down/press-count-down.vue';
import CountTo from './packages/press-count-to/press-count-to.vue';
import DatetimePicker from './packages/press-datetime-picker/press-datetime-picker.vue';
import DialogPlus from './packages/press-dialog-plus/press-dialog-plus.vue';
import Dialog from './packages/press-dialog/press-dialog.vue';
import Divider from './packages/press-divider/press-divider.vue';
import DropdownItem from './packages/press-dropdown-item/press-dropdown-item.vue';
import DropdownMenu from './packages/press-dropdown-menu/press-dropdown-menu.vue';
import Empty from './packages/press-empty/press-empty.vue';
import Fab from './packages/press-fab/press-fab.vue';
import Field from './packages/press-field/press-field.vue';
import FormItem from './packages/press-form-item/press-form-item.vue';
import Form from './packages/press-form/press-form.vue';
import GridItem from './packages/press-grid-item/press-grid-item.vue';
import Grid from './packages/press-grid/press-grid.vue';
import IconPlus from './packages/press-icon-plus/press-icon-plus.vue';
import Icon from './packages/press-icon/press-icon.vue';
import ImagePreview from './packages/press-image-preview/press-image-preview.vue';
import Image from './packages/press-image/press-image.vue';
import IndexAnchor from './packages/press-index-anchor/press-index-anchor.vue';
import IndexBar from './packages/press-index-bar/press-index-bar.vue';
import Info from './packages/press-info/press-info.vue';
import Link from './packages/press-link/press-link.vue';
import List from './packages/press-list/press-list.vue';
import LoadingPlus from './packages/press-loading-plus/press-loading-plus.vue';
import Loading from './packages/press-loading/press-loading.vue';
import NavBar from './packages/press-nav-bar/press-nav-bar.vue';
import NoticeBar from './packages/press-notice-bar/press-notice-bar.vue';
import Notify from './packages/press-notify/press-notify.vue';
import Overlay from './packages/press-overlay/press-overlay.vue';
import Pagination from './packages/press-pagination/press-pagination.vue';
import PickerColumn from './packages/press-picker-column/press-picker-column.vue';
import PickerPlusPopupPlus from './packages/press-picker-plus-popup-plus/press-picker-plus-popup-plus.vue';
import PickerPlus from './packages/press-picker-plus/press-picker-plus.vue';
import PickerView from './packages/press-picker-view/press-picker-view.vue';
import Picker from './packages/press-picker/press-picker.vue';
import PopoverPlus from './packages/press-popover-plus/press-popover-plus.vue';
import Popover from './packages/press-popover/press-popover.vue';
import PopupCell from './packages/press-popup-cell/press-popup-cell.vue';
import PopupPlus from './packages/press-popup-plus/press-popup-plus.vue';
import Popup from './packages/press-popup/press-popup.vue';
import Progress from './packages/press-progress/press-progress.vue';
import Protocol from './packages/press-protocol/press-protocol.vue';
import QRCodePopup from './packages/press-q-r-code-popup/press-q-r-code-popup.vue';
import QRCode from './packages/press-q-r-code/press-q-r-code.vue';
import RadioGroup from './packages/press-radio-group/press-radio-group.vue';
import Radio from './packages/press-radio/press-radio.vue';
import Rate from './packages/press-rate/press-rate.vue';
import Row from './packages/press-row/press-row.vue';
import ScrollView from './packages/press-scroll-view/press-scroll-view.vue';
import Search from './packages/press-search/press-search.vue';
import ShareSheet from './packages/press-share-sheet/press-share-sheet.vue';
import SidebarItem from './packages/press-sidebar-item/press-sidebar-item.vue';
import Sidebar from './packages/press-sidebar/press-sidebar.vue';
import Skeleton from './packages/press-skeleton/press-skeleton.vue';
import Slider from './packages/press-slider/press-slider.vue';
import Stepper from './packages/press-stepper/press-stepper.vue';
import Steps from './packages/press-steps/press-steps.vue';
import Sticky from './packages/press-sticky/press-sticky.vue';
import SwipeCell from './packages/press-swipe-cell/press-swipe-cell.vue';
import SwiperItem from './packages/press-swiper-item/press-swiper-item.vue';
import Swiper from './packages/press-swiper/press-swiper.vue';
import Switch from './packages/press-switch/press-switch.vue';
import Tab from './packages/press-tab/press-tab.vue';
import TabbarItem from './packages/press-tabbar-item/press-tabbar-item.vue';
import Tabbar from './packages/press-tabbar/press-tabbar.vue';
import Tabs from './packages/press-tabs/press-tabs.vue';
import Tag from './packages/press-tag/press-tag.vue';
import Teleport from './packages/press-teleport/press-teleport.vue';
import Text from './packages/press-text/press-text.vue';
import Toast from './packages/press-toast/press-toast.vue';
import Transition from './packages/press-transition/press-transition.vue';
import TreeSelect from './packages/press-tree-select/press-tree-select.vue';
import Uploader from './packages/press-uploader/press-uploader.vue';

const components = {
  Area,
  AvatarGroup,
  Avatar,
  BackTop,
  Badge,
  Barcode,
  Button,
  Calendar,
  Card,
  CellGroup,
  Cell,
  CheckboxGroup,
  Checkbox,
  Circle,
  CodeInput,
  Col,
  CollapseItem,
  Collapse,
  CountDown,
  CountTo,
  DatetimePicker,
  DialogPlus,
  Dialog,
  Divider,
  DropdownItem,
  DropdownMenu,
  Empty,
  Fab,
  Field,
  FormItem,
  Form,
  GridItem,
  Grid,
  IconPlus,
  Icon,
  ImagePreview,
  Image,
  IndexAnchor,
  IndexBar,
  Info,
  Link,
  List,
  LoadingPlus,
  Loading,
  NavBar,
  NoticeBar,
  Notify,
  Overlay,
  Pagination,
  PickerColumn,
  PickerPlusPopupPlus,
  PickerPlus,
  PickerView,
  Picker,
  PopoverPlus,
  Popover,
  PopupCell,
  PopupPlus,
  Popup,
  Progress,
  Protocol,
  QRCodePopup,
  QRCode,
  RadioGroup,
  Radio,
  Rate,
  Row,
  ScrollView,
  Search,
  ShareSheet,
  SidebarItem,
  Sidebar,
  Skeleton,
  Slider,
  Stepper,
  Steps,
  Sticky,
  SwipeCell,
  SwiperItem,
  Swiper,
  Switch,
  Tab,
  TabbarItem,
  Tabbar,
  Tabs,
  Tag,
  Teleport,
  Text,
  Toast,
  Transition,
  TreeSelect,
  Uploader,
};

const install = function (Vue) {
  Object.values(components).forEach((component) => {
    Vue.component(component.name, component);
  });
};

if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  install,
  ...components,
};
export * from './packages/common/public/public';
