/* eslint-disable import/order */
/* Automatically generated by 'press-ui/script/generate-component-config/generate-entry.js' */
import About from './packages/press-about/press-about.vue';
import ActDemo from './packages/press-act-demo/press-act-demo.vue';
import ActionSheet from './packages/press-action-sheet/press-action-sheet.vue';
import Area from './packages/press-area/press-area.vue';
import AreaPopup from './packages/press-area/press-area-popup.vue';
import Avatar from './packages/press-avatar/press-avatar.vue';
import AvatarGroup from './packages/press-avatar-group/press-avatar-group.vue';
import BackTop from './packages/press-back-top/press-back-top.vue';
import Badge from './packages/press-badge/press-badge.vue';
import Barcode from './packages/press-barcode/press-barcode.vue';
import Barrage from './packages/press-barrage/press-barrage.vue';
import Button from './packages/press-button/press-button.vue';
import Calendar from './packages/press-calendar/press-calendar.vue';
import CalendarHeader from './packages/press-calendar-header/press-calendar-header.vue';
import CalendarInner from './packages/press-calendar-inner/press-calendar-inner.vue';
import CalendarMonth from './packages/press-calendar-month/press-calendar-month.vue';
import Card from './packages/press-card/press-card.vue';
import Cascader from './packages/press-cascader/press-cascader.vue';
import Cell from './packages/press-cell/press-cell.vue';
import CellGroup from './packages/press-cell-group/press-cell-group.vue';
import Checkbox from './packages/press-checkbox/press-checkbox.vue';
import CheckboxGroup from './packages/press-checkbox-group/press-checkbox-group.vue';
import Circle from './packages/press-circle/press-circle.vue';
import CodeInput from './packages/press-code-input/press-code-input.vue';
import Col from './packages/press-col/press-col.vue';
import Collapse from './packages/press-collapse/press-collapse.vue';
import CollapseItem from './packages/press-collapse-item/press-collapse-item.vue';
import ColorPicker from './packages/press-color-picker/press-color-picker.vue';
import CountDown from './packages/press-count-down/press-count-down.vue';
import CountTo from './packages/press-count-to/press-count-to.vue';
import Cropper from './packages/press-cropper/press-cropper.vue';
import DatetimePicker from './packages/press-datetime-picker/press-datetime-picker.vue';
import DatetimePickerPopup from './packages/press-datetime-picker/press-datetime-picker-popup.vue';
import DatetimePickerPopupPlus from './packages/press-datetime-picker/press-datetime-picker-popup-plus.vue';
import DemoBlock from './packages/press-demo-block/press-demo-block.vue';
import DemoBlockPlus from './packages/press-demo-block-plus/press-demo-block-plus.vue';
import DemoIndex from './packages/press-demo-index/press-demo-index.vue';
import DemoInput from './packages/press-demo-input/press-demo-input.vue';
import Dialog from './packages/press-dialog/press-dialog.vue';
import DialogPlus from './packages/press-dialog-plus/press-dialog-plus.vue';
import Divider from './packages/press-divider/press-divider.vue';
import DropdownItem from './packages/press-dropdown-item/press-dropdown-item.vue';
import DropdownMenu from './packages/press-dropdown-menu/press-dropdown-menu.vue';
import Empty from './packages/press-empty/press-empty.vue';
import Fab from './packages/press-fab/press-fab.vue';
import Field from './packages/press-field/press-field.vue';
import Form from './packages/press-form/press-form.vue';
import FormItem from './packages/press-form-item/press-form-item.vue';
import Grid from './packages/press-grid/press-grid.vue';
import GridItem from './packages/press-grid-item/press-grid-item.vue';
import Guide from './packages/press-guide/press-guide.vue';
import GuideContent from './packages/press-guide-content/press-guide-content.vue';
import Icon from './packages/press-icon/press-icon.vue';
import IconDelete from './packages/press-icon-delete/press-icon-delete.vue';
import IconMusic from './packages/press-icon-music/press-icon-music.vue';
import IconPlus from './packages/press-icon-plus/press-icon-plus.vue';
import Image from './packages/press-image/press-image.vue';
import ImagePreview from './packages/press-image-preview/press-image-preview.vue';
import IndexAnchor from './packages/press-index-anchor/press-index-anchor.vue';
import IndexBar from './packages/press-index-bar/press-index-bar.vue';
import Info from './packages/press-info/press-info.vue';
import Link from './packages/press-link/press-link.vue';
import List from './packages/press-list/press-list.vue';
import Loading from './packages/press-loading/press-loading.vue';
import LoadingPlus from './packages/press-loading-plus/press-loading-plus.vue';
import NavBar from './packages/press-nav-bar/press-nav-bar.vue';
import NoticeBar from './packages/press-notice-bar/press-notice-bar.vue';
import Notify from './packages/press-notify/press-notify.vue';
import NumberKeyboard from './packages/press-number-keyboard/press-number-keyboard.vue';
import Overlay from './packages/press-overlay/press-overlay.vue';
import Pagination from './packages/press-pagination/press-pagination.vue';
import Picker from './packages/press-picker/press-picker.vue';
import PickerColumn from './packages/press-picker-column/press-picker-column.vue';
import PickerPlus from './packages/press-picker-plus/press-picker-plus.vue';
import PickerPopup from './packages/press-picker-popup/press-picker-popup.vue';
import PickerToolbar from './packages/press-picker-toolbar/press-picker-toolbar.vue';
import PickerView from './packages/press-picker-view/press-picker-view.vue';
import Popover from './packages/press-popover/press-popover.vue';
import PopoverPlus from './packages/press-popover-plus/press-popover-plus.vue';
import Popup from './packages/press-popup/press-popup.vue';
import PopupCell from './packages/press-popup-cell/press-popup-cell.vue';
import PopupPlus from './packages/press-popup-plus/press-popup-plus.vue';
import Progress from './packages/press-progress/press-progress.vue';
import Protocol from './packages/press-protocol/press-protocol.vue';
import PullRefresh from './packages/press-pull-refresh/press-pull-refresh.vue';
import QRCode from './packages/press-q-r-code/press-q-r-code.vue';
import QRCodePopup from './packages/press-q-r-code-popup/press-q-r-code-popup.vue';
import Radio from './packages/press-radio/press-radio.vue';
import RadioGroup from './packages/press-radio-group/press-radio-group.vue';
import Rate from './packages/press-rate/press-rate.vue';
import RollingText from './packages/press-rolling-text/press-rolling-text.vue';
import RollingTextItem from './packages/press-rolling-text-item/press-rolling-text-item.vue';
import Row from './packages/press-row/press-row.vue';
import ScrollView from './packages/press-scroll-view/press-scroll-view.vue';
import Search from './packages/press-search/press-search.vue';
import Section from './packages/press-section/press-section.vue';
import ShareOptions from './packages/press-share-options/press-share-options.vue';
import ShareSheet from './packages/press-share-sheet/press-share-sheet.vue';
import Sidebar from './packages/press-sidebar/press-sidebar.vue';
import SidebarItem from './packages/press-sidebar-item/press-sidebar-item.vue';
import Signature from './packages/press-signature/press-signature.vue';
import Skeleton from './packages/press-skeleton/press-skeleton.vue';
import Slider from './packages/press-slider/press-slider.vue';
import Stepper from './packages/press-stepper/press-stepper.vue';
import Steps from './packages/press-steps/press-steps.vue';
import Sticky from './packages/press-sticky/press-sticky.vue';
import Style from './packages/press-style/press-style.vue';
import SwipeCell from './packages/press-swipe-cell/press-swipe-cell.vue';
import Swiper from './packages/press-swiper/press-swiper.vue';
import SwiperItem from './packages/press-swiper-item/press-swiper-item.vue';
import Switch from './packages/press-switch/press-switch.vue';
import Tab from './packages/press-tab/press-tab.vue';
import Tabbar from './packages/press-tabbar/press-tabbar.vue';
import TabbarItem from './packages/press-tabbar-item/press-tabbar-item.vue';
import Tabs from './packages/press-tabs/press-tabs.vue';
import Tag from './packages/press-tag/press-tag.vue';
import Teleport from './packages/press-teleport/press-teleport.vue';
import TeleportWeb from './packages/press-teleport-web/press-teleport-web.vue';
import Text from './packages/press-text/press-text.vue';
import TextEllipsis from './packages/press-text-ellipsis/press-text-ellipsis.vue';
import Toast from './packages/press-toast/press-toast.vue';
import ToggleHeader from './packages/press-toggle-header/press-toggle-header.vue';
import Transition from './packages/press-transition/press-transition.vue';
import TreeSelect from './packages/press-tree-select/press-tree-select.vue';
import Ui from './packages/press-ui/press-ui.vue';
import Uploader from './packages/press-uploader/press-uploader.vue';

const components = {
  About,
  ActDemo,
  ActionSheet,
  Area,
  AreaPopup,
  Avatar,
  AvatarGroup,
  BackTop,
  Badge,
  Barcode,
  Barrage,
  Button,
  Calendar,
  CalendarHeader,
  CalendarInner,
  CalendarMonth,
  Card,
  Cascader,
  Cell,
  CellGroup,
  Checkbox,
  CheckboxGroup,
  Circle,
  CodeInput,
  Col,
  Collapse,
  CollapseItem,
  ColorPicker,
  CountDown,
  CountTo,
  Cropper,
  DatetimePicker,
  DatetimePickerPopup,
  DatetimePickerPopupPlus,
  DemoBlock,
  DemoBlockPlus,
  DemoIndex,
  DemoInput,
  Dialog,
  DialogPlus,
  Divider,
  DropdownItem,
  DropdownMenu,
  Empty,
  Fab,
  Field,
  Form,
  FormItem,
  Grid,
  GridItem,
  Guide,
  GuideContent,
  Icon,
  IconDelete,
  IconMusic,
  IconPlus,
  Image,
  ImagePreview,
  IndexAnchor,
  IndexBar,
  Info,
  Link,
  List,
  Loading,
  LoadingPlus,
  NavBar,
  NoticeBar,
  Notify,
  NumberKeyboard,
  Overlay,
  Pagination,
  Picker,
  PickerColumn,
  PickerPlus,
  PickerPopup,
  PickerToolbar,
  PickerView,
  Popover,
  PopoverPlus,
  Popup,
  PopupCell,
  PopupPlus,
  Progress,
  Protocol,
  PullRefresh,
  QRCode,
  QRCodePopup,
  Radio,
  RadioGroup,
  Rate,
  RollingText,
  RollingTextItem,
  Row,
  ScrollView,
  Search,
  Section,
  ShareOptions,
  ShareSheet,
  Sidebar,
  SidebarItem,
  Signature,
  Skeleton,
  Slider,
  Stepper,
  Steps,
  Sticky,
  Style,
  SwipeCell,
  Swiper,
  SwiperItem,
  Switch,
  Tab,
  Tabbar,
  TabbarItem,
  Tabs,
  Tag,
  Teleport,
  TeleportWeb,
  Text,
  TextEllipsis,
  Toast,
  ToggleHeader,
  Transition,
  TreeSelect,
  Ui,
  Uploader,
};

const install = function (Vue) {
  Object.values(components).forEach((component) => {
    Vue.component(component.name, component);
  });
};

if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  install,
  ...components,
};
export * from './packages/common/public/public';
