export declare const TIP_CLASS_MAP: {
  cover: string;
  dialog: string;
  'full-page': string;
  'full-page--portrait': string;
  content: string;
  'content--received': string;
  'content--get': string;
  center: string;
  'center-item': string;
  'base-info': string;
  'goods-name': string;
  'goods-desc': string;
  'button-wrap': string;
  'btn--medium-secondary': string;
  'btn--sure': string;
  'btn--cancel': string;
  'btn--large-primary': string;
  'btn--large-secondary': string;
  'received-box': string;
  'received-title': string;
  'received-content': string;
  'received-status': string;
  'received-name': string;
  'received-img': string;
  'tip-wrap': string;
  'tip-name': string;
  'button-box': string;
  'stay-out': string;
  'height-line': string;
  'stay-out-new': string;
  tips: string;
  'sub-wrap': string;
  sub: string;
};
export declare function getActClass(useTipClass: boolean, args: any): any;
